package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorApp.idl
* Sunday, 10 May, 2026 3:46:48 PM IST
*/

public interface CalculatorOperations 
{
  float add (float a, float b);
  float subtract (float a, float b);
  float multiply (float a, float b);
  float divide (float a, float b);
} // interface CalculatorOperations
